server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; 
    }

    # BẤT CỨ KHI NÀO có một luồng dữ liệu đòi đi vào thư mục /api/...
    location /api/ {
        # Nginx sẽ đẩy luồng dữ liệu đó sang container có tên là "cloud_api", cổng 8000
        # (Đây chính là tên container Backend của bạn)
        proxy_pass http://cloud_api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}