
# ==============================================================================
# LƯU Ý QUAN TRỌNG TRƯỚC KHI CHẠY:
# Hệ thống Edge và Cloud sử dụng chung một mạng lưới để giao tiếp với nhau.
# Do đó, bạn BẮT BUỘC phải tạo mạng này bằng tay trước khi chạy Docker Compose.
#
# Hãy copy và chạy lệnh dưới đây vào Terminal:
# docker network create ppe_shared_net
# ==============================================================================

services:
  edge_db:
    image: postgres:13
    container_name: edge_db
    # Lấy thông số user, pass, db name từ file .env
    env_file:
      - .env
    ports:
      # Lấy biến DB_HOST_PORT từ .env, nếu không có thì mặc định dùng 5436
      - "${DB_HOST_PORT:-5436}:5432"
    volumes:
      - edge_pgdata:/var/lib/postgresql/data
    networks:
      - ppe_shared_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ppe_db_edge"]
      interval: 3s
      timeout: 3s
      retries: 5
  
  edge_mqtt:
    image: eclipse-mosquitto:2.0
    container_name: edge_mqtt
    ports:
      - "${MQTT_HOST_PORT:-1885}:1883"
      - "9002:9001"
    command: mosquitto -c /mosquitto-no-auth.conf
    volumes:
      - ./mosquitto.conf:/mosquitto-no-auth.conf
    networks:
      - ppe_shared_net

  edge_ai:
    build: .
    container_name: edge_ai
    ports:
      - "${EDGE_AI_PORT:-8001}:8001"
    depends_on:
      edge_db:
        condition: service_healthy
      edge_mqtt:
        condition: service_started
    env_file:
      - .env
    volumes:
      - .:/app 
    networks:
      - ppe_shared_net
    devices:
      - "/dev/video0:/dev/video0"
      # - "/dev/video4:/dev/video4"

volumes:
  edge_pgdata:

networks:
  ppe_shared_net:
    external: true