listener 1883
allow_anonymous true


# ==========================================
# CẤU HÌNH BRIDGE ĐỒNG BỘ LÊN CLOUD
# ==========================================
connection edge_to_cloud_bridge

# Tên container của Cloud MQTT và cổng nội bộ
address web_mqtt:1883

# Cấu hình đồng bộ Topic (2 chiều)
# Cú pháp: topic <tên_topic> <hướng_đồng_bộ> <QoS>
# topic edge/# both 0
# topic server/# both 0

# (Tùy chọn) Nếu bạn muốn đồng bộ TẤT CẢ các topic bất kỳ, dùng dòng dưới đây thay cho 2 dòng trên:
topic # both 0