version: '3.8'

services:
  web_db:
    image: postgres:13
    container_name: web_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ppe_db
    ports:
      - "5433:5432"
    volumes:
      - web_pgdata:/var/lib/postgresql/data
    networks:
      - ppe_shared_net
  
  web_mqtt:
    image: eclipse-mosquitto:2.0
    container_name: web_mqtt
    ports:
      - "1884:1883"
      - "9001:9001"
    command: mosquitto -c /mosquitto-no-auth.conf
    volumes:
      - ./mosquitto.conf:/mosquitto-no-auth.conf
    networks:
      - ppe_shared_net

  cloud_api:
    build: .
    container_name: cloud_api
    ports:
      - "8000:8000"
    depends_on:
      - web_db
      - web_mqtt
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:123456@web_db:5432/ppe_db
      MQTT_BROKER: web_mqtt
      MQTT_PORT: 1883
      EDGE_NODE_1_URL: http://edge_ai:8001
    volumes:
      - ./static_images:/app/static_images
    networks:
      - ppe_shared_net

volumes:
  web_pgdata:

networks:
  ppe_shared_net:
    external: true