# Generated by Django 5.2.14 on 2026-05-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian')),
                ('violation_type', models.CharField(choices=[('NO_CARD', 'Khong deo the nhan vien'), ('NO_MASK', 'Khong deo khau trang')], default='NO_CARD', max_length=20)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Duong dan anh')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
