# Generated by Django 5.2.14 on 2026-05-31 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_systemacount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemacount',
            old_name='password',
            new_name='password_hash',
        ),
    ]
