# Generated by Django 5.2.14 on 2026-05-31 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_rename_password_systemacount_password_hash'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemAcount',
            new_name='SystemAccount',
        ),
    ]
