# Generated by Django 5.2.14 on 2026-06-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_rename_systemacount_systemaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Thoi gian bat dau ghi hinh')),
                ('video_path', models.CharField(max_length=255, verbose_name='Duong dan file video')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
